name: Update Project Structure
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Permite l'esecuzione manuale
  schedule:
    - cron: '0 0 * * *'  # Esecuzione giornaliera

jobs:
  update-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tree
        run: sudo apt-get install -y tree

      - name: Generate structure
        run: |
          tree -I 'build|bin|*~' --dirsfirst -n > STRUCTURE.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update project structure"
          branch: master
